### ISSUE TITLE
Force Closing after submission of Symptoms

### ISSUE THREAD

**Issue by Earl404** [zemahran/android-medical-assistant#1]
The App after running crashes when the symptoms are submitted, this is the logcat:

`2019-03-23 15:09:38.295 24477-24477/com.example.yomna.symptomate D/nfndskjfnjkdsn: Your symptoms are :
    Bleeding gums
2019-03-23 15:09:56.776 24477-24590/com.example.yomna.symptomate W/System.err: java.io.FileNotFoundException: https://young-retreat-26153.herokuapp.com/chat
2019-03-23 15:09:56.776 24477-24590/com.example.yomna.symptomate W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
2019-03-23 15:09:56.776 24477-24590/com.example.yomna.symptomate W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2019-03-23 15:09:56.776 24477-24590/com.example.yomna.symptomate W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
2019-03-23 15:09:56.779 24477-24590/com.example.yomna.symptomate W/System.err:     at com.example.yomna.symptomate.Chat.doInBackground(Chat.java:39)
2019-03-23 15:09:56.779 24477-24590/com.example.yomna.symptomate W/System.err:     at com.example.yomna.symptomate.Chat.doInBackground(Chat.java:19)
2019-03-23 15:09:56.779 24477-24590/com.example.yomna.symptomate W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-03-23 15:09:56.779 24477-24590/com.example.yomna.symptomate W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-03-23 15:09:56.780 24477-24590/com.example.yomna.symptomate W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-03-23 15:09:56.780 24477-24590/com.example.yomna.symptomate W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-03-23 15:09:56.780 24477-24590/com.example.yomna.symptomate W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-03-23 15:09:56.780 24477-24590/com.example.yomna.symptomate W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-03-23 15:09:56.799 24477-24477/com.example.yomna.symptomate D/AndroidRuntime: Shutting down VM
2019-03-23 15:09:56.802 24477-24477/com.example.yomna.symptomate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.yomna.symptomate, PID: 24477
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
        at com.example.yomna.symptomate.MainActivity.ServerChat(MainActivity.java:98)
        at com.example.yomna.symptomate.Chat.onPostExecute(Chat.java:60)
        at com.example.yomna.symptomate.Chat.onPostExecute(Chat.java:19)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-03-23 15:09:56.821 24477-24477/com.example.yomna.symptomate I/Process: Sending signal. PID: 24477 SIG: 9`

**Comment by ghost** [comment]
Anyone?

**Comment by shyam9989** [comment]
The App after running crashes when the symptoms are submitted, this is the logcat:

**Comment by shyam9989** [comment]
The App after running crashes when the symptoms are submitted

**Comment by GeetShingi** [comment]
Did anyone found out how to fix the above bug

**Comment by Zhoha28** [comment]
Did anyone find how to fix the bug???

**Comment by gptshubham595** [comment]
Did anyone?

**Comment by Aishwarya0108** [comment]
java.io.FileNotFoundException: https://young-retreat-26153.herokuapp.com/chat

FileNotFoundException is only thrown when making a network call if a 404 is thrown by the server. Some bad server implementations throw 404 even if you use a method that is not allowed, that is using GET instead of POST.

This is the exception. Probably the file has been removed from the source or its security settings have been changed..

**Comment by hamirbutt** [comment]
has anyone managed to fix this???
